version: "3.5"

networks:
  public:

services:
  c_database:
    image: postgres
    container_name: c_database
    hostname: database
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apivendas
    ports:
      - "5432:5432"
    networks:
      - public
  
  c_app:
    build: .
    command: npm run start:dev
    container_name: c_app
    hostname: app
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    networks:
      - public
    depends_on:
      - c_database
