version: "3.5"

networks:
  public:

services:
  c_database:
    image: postgres
    container_name: apivendas
    hostname: apivendas
    environment: 
      - POSTGRES_USER=apivendas
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    networks:
      - public
  
  c_app:
    build: .
    command: yarn dev
    container_name: c_app
    hostname: app
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    networks:
      - public
    depends_on:
      - c_database
